### ISSUE TITLE
Move hardcoded Pokemon information

### ISSUE THREAD

**Issue by ed-george** [Shad0wShayd3/Pydex#1]
Consider moving hardcoded information from `pokeloc_en.py` into a more flexible structure such as a JSON file and then parse it. Information can then be added/removed with ease and without modification of any python code.

**Comment by Shad0wShayd3** [comment]
This isn't a bad idea, but I'll need to brush up on my JSON.

**Comment by Shad0wShayd3** [comment]
We will no longer be supporting localization files.
