### ISSUE TITLE
Use existing service for information

### ISSUE THREAD

**Issue by ed-george** [Shad0wShayd3/Pydex#2]
Using an external source for data, such as [Pokéapi](http://pokeapi.co/) might be worth looking at.

There are 1001 different things you could do with it, but it has a surplus of useful information in any case.

**Comment by Shad0wShayd3** [comment]
Not only is this amazing for the sense that we don't have to copy down 718 Pokedex entries, but there is even a Python wrapper for this called [pykemon](https://github.com/phalt/pykemon). It looks like it's broken on newer versions of Python, but there is a fix, going to try it and see if I can mod it to work how I'd like.

**Comment by Shad0wShayd3** [comment]
PokeAPI has been wrapped into the program.
